### ISSUE TITLE
Is RSAParametersWithPrivate really required?

### ISSUE THREAD

**Issue by bragma** [mrsheepuk/ASPNETSelfCreatedTokenAuthExample#6]
Hi,
I was making some tests with this project and I fail to understand the purpose of the RSAParametersWithPrivate class. It seems to me I can generate an RSAParameters object with all fields populated simply by deserializing it:

JsonConvert.DeserializeObject<RSAParameters>("<JSON params string here>");

The RSAParametersWithPrivate class does not seem to add anything to this. Am I missing something?

**Comment by mrsheepuk** [comment]
It's possible that the RSAParameters class has changed in the latest RC,
but when this was first implemented the private key details were missing if
you serialised/deserialised using the RSAParameters class.

When I'm back to a computer in a few days I'll do a couple of tests to see
if it's still necessary.

**Comment by bragma** [comment]
Thanks! I didn't have time to make in depth tests, but serializing both classes produced exactly the same JSON. In fact, I was about to ask which "details" are part of the private key.
Enjoy your vacations! ;-)

**Comment by geertendoornenbal** [comment]
I can verify this, I used the code from the repository, but upon seeing this issue I removed the RSAParametersWithPrivate class (and the code associated with it), and could immediately continue using the same file.
So the serialization result is indeed exactly the same.

**Comment by rwasef1830** [comment]
Yes, it is required because on .NET 4.6, all properties except "Exponent" and "Modulus" (which are the "public" key part) are marked as [NonSerializable] and JSON.net honors this, so it won't serialize them or restore them.

On .NET Core the entire old serialization system was scrapped and RSAParameters no longer has those attributes on them, so all properties are round-tripped.

For the code to work properly on both platforms a custom class should be used instead of the built-in System.Security.Cryptography.RSAParameters struct.

edit: It appears that the NuGet package System.Security.Cryptography.Algorithms contains the version of RSAParameters without the serialization attributes (this is for .NET Core)

**Comment by bragma** [comment]
+1
Correct, I've just seen the problem today in a project.

**Comment by mrsheepuk** [comment]
Sounds like the answer is "yes" then, I'll close this for now.
